import type { Metadata } from "next";
import { Inter, Arimo } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const arimo = Arimo({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark ">
      <body className={cn(arimo.className, "font-medium")}>
        <main>
          <Toaster />
          <NextTopLoader showSpinner={false} color="#8d8dff" />

          {children}
        </main>
      </body>
    </html>
  );
}
