import type { Metadata } from "next";
import { Inter, Arimo } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils";
import Header from "./components/header/Header";
import { ThemeProvider } from "@/theme/ThemeProvider";
import { ThemeToggler } from "@/theme/ThemeToggler";

const inter = Inter({ subsets: ["latin"] });
const arimo = Arimo({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={cn(arimo.className, "font-medium")}>
        <main>
          <Toaster />
          <NextTopLoader showSpinner={false} color="#8d8dff" />
          <ThemeProvider
            attribute="class"
            disableTransitionOnChange
            enableSystem
          >
            <ThemeToggler />
            <Header />
            {children}
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
